name: Build
on:
  push:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Set short git commit SHA
      id: vars
      run: |
        echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: containers.renci.org
        username: ${{ secrets.CONTAINERHUB_USERNAME }}
        password: ${{ secrets.CONTAINERHUB_TOKEN }}
        logout: true

    # The wants code client will check the tag as well ensuring it pulls the correct image.
    - name: Build Push Container
      uses: docker/build-push-action@v5
      with:
        push: true
        # Push to renci-registry and dockerhub here.
        # cache comes from dockerhub.
        tags: |
          containers.renci.org/helxplatform/ottergrader/gradebuild:${{ steps.vars.outputs.short_sha }}
          containers.renci.org/helxplatform/ottergrader/gradebuild:latest
        cache-from: type=registry,ref=helxplatform/ottergrader/gradebuild:buildcache
        cache-to: type=registry,ref=helxplatform/ottergrader/gradebuild:buildcache,mode=max